"""Pre-build step for the documentation.

This script runs *before* the built-in ``repo docs`` command (via the
``./repo.sh docs_gen`` wrapper defined in ``docs_gen.py``). Put any
documentation generation that must happen ahead of Sphinx here.

Importing the ``usd_optimize`` Python API requires the built libraries to be on
``PYTHONPATH`` and the native loader path (``LD_LIBRARY_PATH`` on Linux,
``DYLD_LIBRARY_PATH`` on macOS). Because the native loader reads those variables
at process startup, they cannot be set after this process is already running. So
this script *re-runs itself* under the build's bundled Python interpreter (spawned
as a child process, waited on, and its exit code propagated) with the environment
configured up front (guarded by a sentinel env var to avoid infinite recursion).
Both the ``docs_gen`` wrapper and a direct ``python tools/repoman/docs_prebuild.py``
invocation go through the same bootstrap.

On Windows the dependent-DLL search differs: since Python 3.8 the loader ignores
``PATH`` for an extension module's dependencies and uses directories registered
via ``os.add_dll_directory()`` instead. So the library directories are also
registered that way (see ``_register_dll_directories``) right before the import.

The runtime paths mirror ``[repo_docs] library_paths`` / ``python_paths`` /
``python_path`` in ``repo.toml`` — keep them in sync if those change.
"""

import os
import platform
import subprocess
import sys

# Sentinel: set once we've re-execed into the configured bundled interpreter.
_BOOTSTRAP_ENV = "USD_OPTIMIZE_DOCS_PREBUILD_BOOTSTRAPPED"
# Config can be overridden (e.g. by docs_gen) to match the `docs` --config.
_CONFIG_ENV = "USD_OPTIMIZE_DOCS_CONFIG"

_DEFAULT_CONFIG = "release"

# The validator docs are generated by importing ``usd_optimize.validators``, which
# imports ``usd_validation_nvidia``. That package is not part of the build, so it
# must be pip-installed into the bundled interpreter before the import. Keep the
# version constraint in sync with tools/pyproject/pyproject.toml.
_VALIDATION_PACKAGE = "usd-validation-nvidia>=1.21.0"


def _host_platform() -> str:
    """Return the repo build platform token, e.g. ``linux-x86_64``."""
    system = {"Linux": "linux", "Windows": "windows", "Darwin": "macos"}.get(
        platform.system(), platform.system().lower()
    )
    machine = platform.machine().lower()
    arch = {"amd64": "x86_64", "arm64": "aarch64"}.get(machine, machine)
    return f"{system}-{arch}"


def _config() -> str:
    return os.environ.get(_CONFIG_ENV, _DEFAULT_CONFIG)


def _bundled_python(root: str) -> str:
    exe = "python.exe" if sys.platform == "win32" else "python"
    return os.path.join(root, "_build", "target-deps", "python", exe)


def _runtime_paths(root: str):
    """Return (python_paths, library_paths) for importing ``usd_optimize``.

    Mirrors ``[repo_docs]`` ``python_paths`` / ``library_paths`` in repo.toml.
    """
    plat = _host_platform()
    config = _config()
    build = os.path.join(root, "_build", plat, config)
    usd = os.path.join(root, "_build", "target-deps", "usd", config)

    python_paths = [
        os.path.join(build, "python"),
        os.path.join(usd, "lib", "python"),
    ]
    library_paths = [
        os.path.join(build, "lib"),
        os.path.join(build, "extraLibs"),
        os.path.join(usd, "lib"),
        # Only needed for USD 25.05: that Windows package keeps its third-party
        # runtime DLLs (TBB, Imath, OpenEXR, ...) in usd/bin rather than usd/lib,
        # so usd_tf.dll can't resolve tbb.dll without it. No-op on 25.11.
        os.path.join(usd, "bin"),
    ]
    return python_paths, library_paths


def _native_lib_env_var() -> str:
    if sys.platform == "win32":
        return "PATH"
    return "LD_LIBRARY_PATH"


def _build_env(root: str) -> dict:
    """Return a copy of os.environ with runtime paths prepended."""
    python_paths, library_paths = _runtime_paths(root)
    env = dict(os.environ)

    def prepend(var: str, paths):
        existing = env.get(var, "")
        parts = [p for p in paths if p]
        if existing:
            parts.append(existing)
        env[var] = os.pathsep.join(parts)

    prepend("PYTHONPATH", python_paths)
    prepend(_native_lib_env_var(), library_paths)
    env[_BOOTSTRAP_ENV] = "1"
    return env


def _register_dll_directories(root: str) -> None:
    """Make ``usd_optimize``'s dependent DLLs resolvable on Windows.

    Since Python 3.8, ``PATH`` is no longer searched when resolving the
    dependent DLLs of an extension module (``.pyd``); the loader uses the
    directories registered via ``os.add_dll_directory()`` instead. Prepending to
    ``PATH`` (see ``_build_env``) is therefore not enough on Windows — without
    this the ``usd_optimize.core`` import fails with a cryptic "DLL load failed".
    No-op on non-Windows, where ``LD_LIBRARY_PATH`` already covers this.
    """
    if sys.platform != "win32" or not hasattr(os, "add_dll_directory"):
        return
    _, library_paths = _runtime_paths(root)
    for path in library_paths:
        if path and os.path.isdir(path):
            os.add_dll_directory(path)


def _ensure_validation_package(python: str, env: dict) -> None:
    """Install ``usd-validation-nvidia`` into the bundled interpreter.

    The validator docs are generated by importing ``usd_optimize.validators``,
    which in turn imports ``usd_validation_nvidia``. That package is not produced
    by the build, so pip-install it into the bundled interpreter. pip enforces the
    floor; a presence check would skip an older install. Mirrors
    ``tools/validators/run.sh``.
    """
    print(f"[docs_prebuild] ensuring {_VALIDATION_PACKAGE} in bundled interpreter")
    result = subprocess.run(
        [python, "-m", "pip", "install", "--disable-pip-version-check", _VALIDATION_PACKAGE],
        env=env,
        capture_output=True,
        text=True,
    )
    print(result.stdout)
    print(result.stderr)
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to install {_VALIDATION_PACKAGE} (exit code {result.returncode})"
        )


def _bootstrap(root: str) -> None:
    """Re-run under the bundled interpreter with the runtime env configured.

    No-op if we are already in the bootstrapped subprocess. Otherwise spawns the
    bundled interpreter as a child process (with the native loader path set up
    front), waits for it, and exits with its return code — so this function never
    returns in the parent process.

    We use ``subprocess`` rather than ``os.execve`` because ``execve`` does not
    behave like a POSIX exec on Windows: instead of replacing the current
    process, it spawns a *detached* child and the original process returns/exits
    immediately. The launching process would then terminate while the real work
    ran independently, making the job look like it had finished (or failed)
    before docs generation completed. ``subprocess.run`` + propagating the exit
    code works consistently across platforms.
    """
    if os.environ.get(_BOOTSTRAP_ENV):
        return

    python = _bundled_python(root)
    if not os.path.isfile(python):
        raise FileNotFoundError(
            f"Bundled Python not found at {python}. Run `./repo.sh build` first "
            "so the usd_optimize libraries and interpreter are available."
        )

    env = _build_env(root)
    # The validator docs import ``usd_validation_nvidia``, which is not part of the
    # build. Ensure it is installed into the bundled interpreter before we re-exec
    # into it, so the import in the bootstrapped subprocess resolves.
    _ensure_validation_package(python, env)
    # Spawn the bundled interpreter so the native loader picks up the new library
    # path from the start, wait for it, and mirror its exit code.
    result = subprocess.run([python, os.path.abspath(__file__), root], env=env, capture_output=True, text=True)
    print(result.stderr)
    print(result.stdout)
    sys.exit(result.returncode)


def _python_operation_keys(root: str) -> set:
    """Return the set of operation keys implemented as Python plugins.

    Python operations live under ``source/operations/<key>/`` as a directory
    containing an ``__init__.py`` (this mirrors ``source/operations/premake5.lua``,
    which discovers them by globbing ``**__init__.py``). Unlike the C++ ``.so``
    plugins, these only register when a Python interpreter is initialized, so they
    are available via the ``usd-optimize`` Python wheel / bindings but not from the
    standalone ``usdOptimize`` CLI (which never initializes Python). We flag them in
    the generated docs so the catalog distinguishes them from CLI-available ops.
    """
    ops_dir = os.path.join(root, "source", "operations")
    keys = set()
    if os.path.isdir(ops_dir):
        for name in os.listdir(ops_dir):
            if os.path.isfile(os.path.join(ops_dir, name, "__init__.py")):
                keys.add(name)
    return keys


def _gen_operations_docs(root: str):
    # we're going to use usd_optimize core python apis to generate documentation
    # for operations
    from usd_optimize.core import UsdOptimizeCore
    uo_core = UsdOptimizeCore.getInstance()

    # operations implemented as Python plugins are available via the wheel /
    # bindings but not the native CLI; flag them in the generated docs.
    python_op_keys = _python_operation_keys(root)

    # we need to do a first pass to gather all the information we need
    op_names = []
    op_info = {}
    for op_key in uo_core.getOperations():
        # we key info off the actual operation display name so we can make sure
        # they're alphabetically sorted in the docs
        op_display_name = uo_core.getOperationDisplayName(op_key)
        op_names.append(op_display_name)

        # build out the info for the operation args
        arg_info = []
        args = uo_core.getOperationArguments(op_key)
        for arg in args:
            # groups can be skipped in the docs since they're for UI
            if "group" in arg:
                continue
            # get the metadata of this arg so we can check if its visible, since
            # invisible args should be skipped in the docs
            arg_metadata = arg.get("metadata", {})
            if arg_metadata.get("visible", True) is False or "group" in arg_metadata:
                continue
            # resolve name
            arg_name = f"{arg['name']}"
            # resolve the default value (and the type from this)
            arg_default_value = arg.get("defaultValue", "")
            arg_type = type(arg_default_value)
            # if this is a list, we want to find the type of list
            if arg_type == list:
                arg_array_type = arg.get("arrayType", 0)
                if arg_array_type == 1:
                    arg_type = "[int]"
                elif arg_array_type == 2:
                    arg_type = "[string]"
                elif arg_array_type == 3 or arg_array_type == 4:
                    arg_type = "[float]"
                else:
                    arg_type = "list"
            # otherwise just use the name of the python type
            else:
                arg_type = arg_type.__name__
            # clean up the default value for display in the docs.
            if isinstance(arg_default_value, str):
                cleaned_default_value = arg_default_value.replace("\n", " ")
                arg_default_value = f'"{cleaned_default_value}"'
            elif isinstance(arg_default_value, float):
                arg_default_value = f"{arg_default_value:.6g}"
            # build out the info
            arg_info.append({
                "name": arg_name,
                "displayName": arg["displayName"],
                "type": arg_type,
                "defaultValue": arg_default_value,
                "enums": arg.get("enums", None),
                "min": arg_metadata.get("min", None),
                "max": arg_metadata.get("max", None),
                "description": arg.get("description", ""),
            })

        # build the info for this operation
        op_info[op_display_name] = {
            "key": op_key,
            "description": uo_core.getOperationDescription(op_key),
            "documentation": uo_core.getOperationDocumentation(op_key),
            "visible": uo_core.getOperationVisible(op_key),
            "args": arg_info,
        }

    # sort the operation names alphabetically for display in the docs
    op_names.sort()

    indent = "    "

    # first generate the main table of contents and the summary table for the
    # operations overview
    toc_tree = f".. toctree::\n{indent}:hidden:\n{indent}:maxdepth: 1\n{indent}:caption: Operations\n\n"

    # Build the summary rows first so the reStructuredText simple table can be
    # sized to its widest cell. In a simple table the column rules (===) must be
    # at least as wide as the content, so a fixed column width breaks parsing
    # once a tag such as "[Developer] [Python only]" makes an entry longer than
    # the reserved width.
    name_header = "Operation"
    desc_header = "Description"
    rows = []
    for op_name in op_names:
        op = op_info[op_name]
        op_key = op["key"]
        # generate toc tree entry (before any tags)
        toc_tree += f"{indent}{op_name} <operations/{op_key}>\n"
        # Python-plugin operations are not available from the native CLI.
        if op_key in python_op_keys:
            op_name += " [Python only]"
        table_name = f":doc:`{op_name}<operations/{op_key}>`"
        rows.append((table_name, op["description"]))

    name_width = max([len(name_header)] + [len(name) for name, _ in rows])
    desc_width = max([len(desc_header)] + [len(desc) for _, desc in rows])
    summary_sep = f"{indent}{'=' * name_width} {'=' * desc_width}"

    summary_table = f".. table::\n    :widths: 30 70\n\n{summary_sep}\n"
    summary_table += f"{indent}{name_header: <{name_width}} {desc_header}\n{summary_sep}\n"
    for table_name, description in rows:
        summary_table += f"{indent}{table_name: <{name_width}} {description}\n"
    summary_table += f"{summary_sep}\n\n"

    # now generate a page for each operation
    op_docs = {}
    for op_name in op_names:
        op = op_info[op_name]
        op_key = op["key"]
        op_doc = ".. AUTO GENERATED FILE - DO NOT EDIT\n\n"
        # write the title
        op_doc += f"{'=' * len(op_name)}\n{op_name}\n{'=' * len(op_name)}\n\n"
        # write the key
        op_doc += f"**Key**: ``{op_key}``\n\n"
        # is this a Python-hosted operation? (unavailable from the native CLI)
        if op_key in python_op_keys:
            op_doc += (
                ".. Note:: **Python-hosted operation**: available through the "
                "``usd-optimize`` Python wheel / bindings, but not the standalone "
                "``usdOptimize`` CLI (which does not initialize a Python interpreter).\n\n"
            )
        # write the documentation
        op_doc += f"{op['documentation']}\n\n"
        # write arguments
        if op["args"]:
            op_doc += "Arguments\n---------\n\n"
            for arg in op["args"]:
                op_doc += f"{arg['displayName']}\n{'^' * len(arg['displayName'])}\n\n"
                op_doc += f"{arg['description']}\n\n"
                op_doc += f"{indent}- Name: ``{arg['name']}``\n"
                op_doc += f"{indent}- Type: ``{arg['type']}``\n"
                op_doc += f"{indent}- Default Value: ``{arg['defaultValue']}``\n"
                if arg.get("enums") is not None:
                    op_doc += f"{indent}- Enum Values:\n"
                    for enum in arg["enums"]:
                        op_doc += f"{indent}{indent}- ``{enum[1]}: {enum[0]}``\n"
                if arg.get("min") is not None:
                    op_doc += f"{indent}- Min Value: ``{arg['min']}``\n"
                if arg.get("max") is not None:
                    op_doc += f"{indent}- Max Value: ``{arg['max']}``\n"
                op_doc += "\n"
        op_docs[op_key] = op_doc

    return (toc_tree, summary_table, op_docs)


def _gen_validator_docs():
    # we're going to use the usd_optimize validators to generate documentation
    # for the performance validators
    from usd_optimize import validators

    docs = "\n"

    # group validators by category
    category_map = {}
    for rule in validators._RULE_CATEGORIES:
        if rule[1] not in category_map:
            category_map[rule[1]] = []
        category_map[rule[1]].append(rule[0])

    for category, rules in category_map.items():
        docs += f"{category}\n{'-' * len(category)}\n\n"
        # insert hardcoded documentation for certain categories
        if category == "Omni:Geometry":
            docs += (
                "These rules check for low-level geometric defects on meshes. "
                "Most are fixed with the "
                ":doc:`Mesh Cleanup<operations/meshCleanup>` operation.\n\n"
            )
        elif category == "Usd:Performance":
            docs += (
                "These rules check for stage- and scene-level conditions that "
                "affect performance.\n\n"
            )
        # generate docs for each validator in this category
        for rule in rules:
            # Strip the output-only "UsdOptimize" __name__ prefix; this page is already scoped to us.
            display_name = rule.__name__.removeprefix("UsdOptimize")
            docs += f"{display_name}\n{'^' * len(display_name)}\n"
            doc_str = rule.__doc__ or ""
            cleaned_doc_str = ""
            for line in doc_str.splitlines():
                # strip leading/trailing whitespace
                line = line.strip()
                # if the line is empty replace with a double newline
                if line == "":
                    cleaned_doc_str += "\n\n"
                # if the line starts with a dash, it's likely a list item and
                # should be on a new line
                elif line.startswith("-"):
                    cleaned_doc_str += "\n" + line + " "
                # otherwise add to the cleaned string with a space rather than new line
                else:
                    cleaned_doc_str += line + " "
            docs += f"{cleaned_doc_str}\n\n"

    return docs 


def _gen_cli_docs(root: str) -> str:
    """Generate the CLI usage section by capturing ``usdOptimize --help``.

    Runs the built ``bin/usdOptimize`` tool with ``--help`` and wraps its output
    in an RST literal block so it can be inserted into ``cli.rst``. Runs in the
    bootstrapped environment, so the native loader path (LD_LIBRARY_PATH etc.)
    is already configured for the tool's dependent libraries.
    """
    plat = _host_platform()
    config = _config()
    exe = "usdOptimize.exe" if sys.platform == "win32" else "usdOptimize"
    binary = os.path.join(root, "_build", plat, config, "bin", exe)
    if not os.path.isfile(binary):
        raise FileNotFoundError(
            f"usdOptimize CLI not found at {binary}. Run `./repo.sh build` first so "
            "the CLI tool is available for docs generation."
        )

    # Decode as UTF-8 (not the system-locale default): the captured help text is
    # written to cli.rst as UTF-8, so any non-ASCII (e.g. an em-dash) must decode
    # consistently here or it would be corrupted on a non-UTF-8 locale.
    result = subprocess.run([binary, "--help"], capture_output=True, text=True, encoding="utf-8")
    # CLI help is written to stdout; fall back to stderr if a tool emits it there.
    help_text = result.stdout or ""
    help_text = help_text.rstrip("\n")
    if not help_text:
        raise RuntimeError(f"`{binary} --help` produced no output (exit code {result.returncode}).")

    # Wrap in an RST literal block: a ``.. code-block:: text`` directive with the
    # help output indented by four spaces so Sphinx renders it verbatim.
    indented = "\n".join(f"    {line}".rstrip() for line in help_text.splitlines())
    # Leading/trailing blank lines keep the directive cleanly separated from the
    # surrounding GENERATED_DOCS markers (matching the other generated sections).
    return f"\n.. code-block:: text\n\n{indented}\n\n"


def _insert_generated_docs(file_path: str, generated_docs: str) -> str:
    """
    Inserts the generated docs into the specified file between the
    GENERATED_DOCS_BEGIN and GENERATED_DOCS_END markers.
    """
    begin_marker = ".. GENERATED_DOCS_BEGIN"
    end_marker = ".. GENERATED_DOCS_END"
    in_generated_section = False

    new_docs = ""

    with open(file_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
        for line in lines:
            # end marker?
            if line.strip().startswith(end_marker):
                in_generated_section = False
            # write the line if we're not in the generated section
            if not in_generated_section:
                new_docs += line
            # begin marker?
            if line.strip().startswith(begin_marker):
                in_generated_section = True
                # generate the operations section of the docs
                new_docs += generated_docs
    
    return new_docs


def run(root: str) -> None:
    """Execute the documentation pre-build step.

    Must run inside the bootstrapped environment (see module docstring) so the
    ``usd_optimize`` import resolves. Call via ``main()`` / ``docs_gen``, or run
    this file directly — both bootstrap first.

    Args:
        root: Absolute path to the repository root.
    """
    docs_dir = os.path.join(root, "docs")

    # On Windows the native loader ignores PATH for dependent DLLs (Python 3.8+),
    # so register the library directories before importing usd_optimize.
    _register_dll_directories(root)

    # first perform doc generation
    (toc_tree, summary_table, op_docs) = _gen_operations_docs(root)

    # open the operations.rst file and insert the generated docs between the
    # markers
    operations_path = os.path.join(docs_dir, "operations.rst")
    operations_docs = _insert_generated_docs(operations_path, toc_tree + "\n\n" + summary_table + "\n")

    # now write the operations.rst back out with the generated content
    with open(operations_path, "w", encoding="utf-8") as f:
        f.write(operations_docs)

    # write out the individual operation docs
    for op_key, op_doc in op_docs.items():
        with open(os.path.join(docs_dir, "operations", f"{op_key}.rst"), "w", encoding="utf-8") as f:
            f.write(op_doc)

    # generate validator docs next
    gen_validator_docs = _gen_validator_docs()

    # open the performance-validators.rst and insert the generated docs between
    # the markers
    validators_path = os.path.join(docs_dir, "performance-validators.rst")
    validators_docs = _insert_generated_docs(validators_path, gen_validator_docs)

    # now write the performance-validators.rst back out with the generated content
    with open(validators_path, "w", encoding="utf-8") as f:
        f.write(validators_docs)

    # generate the CLI usage docs from `usdOptimize --help`
    cli_docs = _gen_cli_docs(root)

    # open the cli.rst and insert the generated usage between the markers
    cli_path = os.path.join(docs_dir, "cli.rst")
    cli_rst = _insert_generated_docs(cli_path, cli_docs)

    # now write the cli.rst back out with the generated content
    with open(cli_path, "w", encoding="utf-8") as f:
        f.write(cli_rst)


def main() -> int:
    # tools/repoman/docs_prebuild.py -> repo root is two levels up.
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    try:
        _bootstrap(root)  # spawns bundled python and exits; returns here only when bootstrapped
    except Exception as e:
        print(f"[docs_prebuild] Bootstrap failed with exception: {e}")
        raise
    try:
        run(root)
    except Exception as e:
        print(f"[docs_prebuild] Pre-build step failed with exception: {e}")
        raise
    return 0


if __name__ == "__main__":
    sys.exit(main())
